### ISSUE TITLE
Use helm dependencies

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#1720]
To ease installation for other users, we should use helm dependencies as part of our Chart. It's unclear if we want to use these for our own deployments.

https://chat.openai.com/share/3a12066b-189a-4723-ab5b-e2da4d7fe9db

**Comment by chaoran-chen** [comment]
@theosanderson, @fhennig, what do you think about this ticket? Is this something that we still would like to do?

**Comment by theosanderson** [comment]
Yes I would say this still makes sense as a ticket to have open

**Comment by fhennig** [comment]
Theo, how is i.e. traefik currently installed? Do we just instruct users to install it on their own? Our chart has i.e. this:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: compression-middleware
spec:
  compress: {}
```

does that mean that the chart won't work if traefik isn't installed?

Haven't looked into it much, so genuinely not sure.
