### ISSUE TITLE
feat(ena-submission): Decide on (sample) metadata fields mapping 

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#2313]
When we submit to ENA they suggest we use metadata fields that they recognize (this isn't necessary we can just submit with arbitrary fields - but will make life easier for the greater community). The standard metadata template for virus data is https://www.ebi.ac.uk/ena/browser/view/ERC000033. I reviewed the entries they propose and would suggest this mapping of the metadata fields we offer on loculus to ENAs metadata fields. 

### Proposed Mapping from ENA fields to loculus fields: 
```yaml
"subject exposure":
  - exposure_event
"type exposure":
  function:
    name: concatenate
    loculus_fields:
      - exposure_setting
      - exposure_details
"hospitalisation":
  loculus_fields:
    - environmental_site
  function:
    name: match
    args: Hospital
  type:
    bool
"illness symptoms":
  - signs_and_symptoms	
"collection date":
  - sample_collection_date
"geographic location (country and/or sea)":
  - geo_loc_country
  type:
    - options: country
"geographic location (region and locality)":
  function:
    name: concatenate
    loculus_fields:
      - geo_loc_admin_1
      - geo_loc_admin_2
"host disease outcome":
  - host_health_outcome
  type: 
  - options: [dead, recovered, recovered with sequelae]
"host common name":
  - host_name_common
"host age":
  - host_age
"host health state":
  - host_health_state
  type: 
  - options: [diseased, healthy, not applicable, not collected, not provided, restricted access, ...]
"host sex":
  - host_gender
  type: 
  - options: [female, hermaphrodite, male, neuter, not applicable, not provided, other, ....]
lab_host:
  - is_lab_host
"host scientific name":
  - host_name_scientific
"collector name":
  - author
"collecting institution":
  function:
    name: concatenate
    loculus_fields:
      - sequenced_by_organization
      - author_affiliations
"receipt date":
  - sample_received_date
isolate:
  - specimen_collector_sample_id
"isolation source host-associated":
  function:
    name: concatenate
    loculus_fields:
      - anatomical_material
      - body_product
      - anatomical_part
"host description":
  function:
    name: concatenate
    loculus_fields:
      - host_vaccination_status
      - host_disease
"host behaviour":
  - host_role
"isolation source non-host-associated":
  function:
    name: concatenate
    loculus_fields:
      - environmental_material
      - food_product
```
I map to most fields in ENA except for the following:

### Suggested fields we will ignore
- sample storage conditions		free text		optional	
- gravidity		free text		optional	
-  host habitat		text choice	recommended	
- virus identifier		free text		recommended	
- subject exposure duration		free text		optional
- personal protective equipment		free text		optional	
- host subject id		free text		mandatory	
- illness duration		free text		optional	
- sample capture status		text choice	recommended	

## Open Questions:

1. We are not filling these fields as they do not have a good counterpart in loculus - maybe we should add them to our metadata fields?
#### Suggested fields maybe we should add?:
- definition for seropositive sample		free text		recommended	
- serotype (required for a seropositive sample)		free text		recommended	

2. We might be able to fill certain fields with more complicated mappings, should we try? We could use the google maps api to get the latitude and longitude from the city name for example and nextclade should give us clade which we could map to strains?:
#### Suggested fields maybe we can fill?:
strain		free text		optional	
geographic location (latitude)		restricted text	recommended	DD
geographic location (longitude)		restricted text	recommended	DD

3. ENA has collector name and collecting institution - in my suggestion above I map this to our author and author affiliation fields - is this ok? Should we add this field to our metadata?
