### ISSUE TITLE
Allow fine-grained control of resources for kubernetes charts

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#2642]
Relates to https://github.com/pathoplexus/pathoplexus/issues/43

I think a nice way to do this might be to have:

Values.yaml:

```
resources:
    [deployment-name]:
         requests:
            memory: "256Mi"
            cpu: "500m"
         limits:
            memory: "512Mi"
            cpu: "1000m"
```

And for any of those set the setting would be taken account of, if set.
