### ISSUE TITLE
Add current schema (after all migrations) to backend docs 

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2791]
Right now we only have 2 files in the backend migrations folder, but they will become more numerous.

For reading the code, it doesn't matter really what all the migration files are, what one cares about is the resulting schema after all migrations are applied. This is currently not easily accessible.

We should create an action that dumps the resulting schema into a docs folder after running flyway on all migrations. This action only needs to run on changes in the flyway migration dir.

Some skeleton generated by Claude:

<details>

```
name: Generate and Commit Flyway Schema

on:
  push:
    paths:
      - 'schema/**'
  pull_request:
    paths:
      - 'schema/**'
  workflow_dispatch:

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Flyway migrations
      uses: docker://flyway/flyway:10-alpine
      env:
        FLYWAY_URL: jdbc:postgresql://postgres:5432/postgres
        FLYWAY_USER: postgres
        FLYWAY_PASSWORD: postgres
      with:
        args: -locations=filesystem:/github/workspace/schema migrate

    - name: Generate schema
      run: |
        docker run --network host -v $PWD:/workspace postgres:16 \
        bash -c "PGPASSWORD=postgres pg_dump -h localhost -U postgres -d postgres --schema-only > /workspace/schema.sql"

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add schema.sql
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update schema based on Flyway migrations" && git push)
```

</details>
