### ISSUE TITLE
Make database secrets more consistent

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2889]
@anna-parker and I were looking into how to get the database name from the config. We were a bit confused that we currently specify secrets for keycloak-database and loculus-database in inconsistent ways:

```
  database:
    type: sealedsecret
    clusterWide: "true"
    encryptedData:
      host: AgDUG
      password: AgCm
      url: AgC
      username: AgAp
  keycloak-database:
    type: sealedsecret
    clusterWide: "true"
    encryptedData:
      addr: AgAw
      database: AgB
      password: AgDB
      port: Ag
      username: AgAuZZ
 ```

For more consistency we should
- rename `database` to `loculus-database`
- use identical fields in encrypted data, i.e. also have `database`, `addr`, `url` ... in `loculus-database` and vice versa
