### ISSUE TITLE
Add ingress route for grafana to toplevel gitops

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2954]
add to https://github.com/loculus-project/loculus_toplevel_gitops

**Comment by corneliusroemer** [comment]
Done:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure  # If you're using a secure entry point like websecure for ArgoCD, keep this, otherwise use "web".
  routes:
    - kind: Rule
      match: Host(`grafana.loculus.org`)
      priority: 10
      services:
        - name: grafana
          port: 80
  tls:
    certResolver: myresolver
```
