### ISSUE TITLE
Prevent parallel backend instances during database migrations

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#3205]
Originally brought up in #3125:

When we deploy a new version, Kubernetes will usually do a rolling update where it first starts the new backend and then shuts down the old one, right? If yes, this means that the old backend could still write “HAS_ERRORS” and “AWAITING_APPROVAL” into the database after the new backend executed the UPDATE query and thereby put the database into an invalid state. Can we somehow avoid having two parallel running backends (at least) if there is a database migration?

**Comment by fhennig** [comment]
Apparently we can do this with either:

```
strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
```

or:

```
strategy:
    type: Recreate
```
