### ISSUE TITLE
Start versioned releases

### ISSUE THREAD

**Issue by fhennig** [loculus-project/loculus#3392]
As a user I want to be able to install software without having to git-clone a repository and I want to know which version of the software I'm running.

**Comment by theosanderson** [comment]
(unimportant nit: I think we probably mostly use "user" to refer to end-users, and "maintainer" for those who install loculus instances)

**Comment by fhennig** [comment]
Hey! I wanted to bump this issue because now I'm working on keeping Loculus up to date in GenSpectrum, and it'd be really nice if I could do rollouts based on released versions of loculus. 

I also noticed that having versions would be quite nice for pinning prepro images:

```
      - version: 1
        image: ghcr.io/loculus-project/preprocessing-nextclade
        args:
          - "prepro"
        configFile:
          log_level: DEBUG
          genes: []
          batch_size: 100
          alignment_requirement: ANY
```

I think it would be a big plus for a stable loculus instance if the image was pinned, so it can't just silently update, but I wouldn't want to pin it to just a random commit. Also having release notes where I can see the changes for the prepro pipeline in particular would be quite nice, so I can immediately see whether I need to do a bump or not.
