### ISSUE TITLE
Loculus specific SMTP and ORCiD settings are in the Helm Chart by default

### ISSUE THREAD

**Issue by fhennig** [loculus-project/loculus#3637]
The `values.yaml` contains:

```yaml
auth:
  smtp:
    host: "in-v3.mailjet.com"
    port: 587
    user: "fafd505de339dd2e9c3e85ad9981af8a"
    replyTo: "noreply@loculus.org"
    from: "noreply@loculus.org"
    envelopeFrom: "noreply@loculus.org"
  verifyEmail: true
  resetPasswordAllowed: true
  registrationAllowed: true
  identityProviders:
    orcid:
      clientId: "APP-P1P7N7T9YVBHQ4EH"
```

Even when overriding the `organisms` to get my own setup, I'll still have this config in there - that seems unexpected. I didn't check, but I think this won't work out of the box?
