### ISSUE TITLE
Helm: Standardize and expand image configuration

### ISSUE THREAD

**Issue by fhennig** [loculus-project/loculus#3726]
I would like to have a way to override specifically the backend image, but more generally probably all images that the Helm Chart uses, and I'd like to be able to do so in a unified way. Additionally I'd like to specify pull policies (i.e. not use 'Always') so I can easily use local images. I want to be able to do this to easily test my own versions of specific components.

Why do I want to do this? I want to use [tilt](https://tilt.dev/) for local testing of specifically the website and backend, and so I need to specify the settings above through the Helm Chart.

### Current situation

Lapis and silo images are specified like this:

```
images:
  lapisSilo: "ghcr.io/genspectrum/lapis-silo:0.5.3"
  lapis: "ghcr.io/genspectrum/lapis:0.3.14"
```

A website image can be specified as `customWebsiteImage`.

For the backend, this is hardcoded: `"ghcr.io/loculus-project/backend:{{ $dockerTag }}"` and the dockerTag can be specified as `loculus.dockerTag`. The imagePullPolicy is not configurable and set to `Always`.

### Proposed new structure

expand the `images` config section with more keys and add `website` and `backend` to it:

```
images:
  lapisSilo:
    repository: "ghcr.io/genspectrum/lapis-silo"
    tag: "0.5.3"
    pullPolicy: "IfNotPresent"

  lapis:
    repository: "ghcr.io/genspectrum/lapis"
    tag: "0.3.14"
    pullPolicy: "IfNotPresent"

  website:
    repository: ...
    tag: ...

  backend: ...

```

This would allow users to configure the settings mentioned above, and also make images be configured in one, unified way. Specifying just the dockerTag for the backend would still be possible, and also we can set imagePullPolicy `Always` as the default, so no functionality would be lost, only structure would change slightly.

It would be a breaking change, but we could also avoid breaking by making the old config settings still valid, just deprecated (to be decided).

### How would it be implemented?
- Adjust values.yaml and schema
- Adjust github Jobs (possibly)
- Maybe adjust the deploy.py script?
