### ISSUE TITLE
bug(ci): integration tests playwright report sometimes outdated

### ISSUE THREAD

**Issue by fhennig** [loculus-project/loculus#3756]
In `integration-tests.yml`:

```yaml
      - name: Run Integration test
        run: |
          set -o pipefail
          cd integration-tests && npx playwright test 2>&1 | tee output.txt
          EXIT_CODE=$?
          echo '```' >> $GITHUB_STEP_SUMMARY
          sed -n '/Running [0-9]\+ tests/,$p' output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          exit $EXIT_CODE
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: integration-tests/playwright-report/
```

The first step shows correct output, but the playwright-report generated in the second step seems to be out of date sometimes.

The report can be downloaded, and also includes a time:

<img width="588" alt="Image" src="https://github.com/user-attachments/assets/bbf819dd-a0e7-4008-8340-1fe437b1e02b" />

The time should be the correct central european time - this is one point where you can see that the report is outdated.
