### ISSUE TITLE
Metadata Schema Missing additionalProperties: false Constraint

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#3770]
# Metadata Schema Missing additionalProperties: false Constraint

## Issue Description

The Loculus Helm Chart values.yaml JSON schema is not correctly validating additional properties in the metadata definition. When adding a new property `includeInDownloadsByDefault` to a metadata field, the schema validation did not catch this addition as an error, even though it wasn't defined in the schema.

## Root Cause

The `metadata` definition in the schema is missing the `additionalProperties: false` constraint. Without this constraint, JSON Schema validation allows any additional properties not explicitly defined in the schema, which can lead to silent additions of unintended properties.

## Current Behavior

```yaml
metadata:
 - name: sampleCollectionDate
   displayName: Collection date
   header: Sample details
   ingest: ncbiCollectionDate
   order: 10
   includeInDownloadsByDefault: true  # This property had not defined in the schema but was accepted
   preprocessing:
     function: parse_date_into_range
     inputs: ...
```

The above configuration is accepted by the schema validator even though `includeInDownloadsByDefault` wasn't defined in the schema.

## Expected Behavior

The schema should reject any undefined properties until they are properly added to the schema definition. This would ensure consistent configuration and prevent typos or misunderstandings.

## Proposed Solution

Add `additionalProperties: false` to the metadata definition in the schema:

```json
"metadata": {
  "type": "object",
  "additionalProperties": false",  // Add this line
  "properties": {
    // existing properties
    "includeInDownloadsByDefault": {
      "groups": ["metadata"],
      "type": "boolean",
      "description": "Whether this field should be included in data downloads by default."
    }
  },
  "required": ["name"]
}
```

## Impact

This change would make the schema more strict and help prevent silent additions of unintended properties, improving the reliability of configurations and making schema errors more discoverable.

## Related

Note that other sections like `ingest` already have `additionalProperties: false` constraints which work properly to prevent undefined properties.
