### ISSUE TITLE
Define file-sharing schema config values.yaml

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#3907]
The values.yaml schema should be extended to contain config for file sharing. For the preview (during development), let's add for the dummy organism:

```yaml
schema:
  submissionFiles: --> What the user uploads
    - name: raw_reads
      multipleFiles: false
  publicFiles: --> What goes into SILO
    - name: raw_reads
      multipleFiles: false
    - name: aligned_reads
      multipleFiles: false
    - name: qc_plots
      multipleFiles: true
```

**Comment by theosanderson** [comment]
We already have `submissionDataTypes` which was originally intended (in broad strokes) to include what is described as `submissionFiles` here.

I'm not clear on the specifics - in reality raw_reads probably would have multiple files? Do we definitely need this property at all?

**Comment by theosanderson** [comment]
I guess `submissionDataTypes` in significant part is used to enable/disable the submission UI elements on the bulk page (and others), so that's the sense in which I imagine this fitting in there. Here essentially I imagine we are adding a "Raw reads" (we probably as ever need a display name) component to the submission form.

Would I imagine that segment data would be added to `submissionDataTypes`? Probably not, because the segment data is used in lots of other places too beyond submission and preprocessing, whereas I imagine this would essentially just be used there. (Some pipelines might assemble the read data and not make the underlying reads public, just the consensus).

**Comment by chaoran-chen** [comment]
How would you then type `submissionDataTypes` exactly? Accepting boolean and a list of values would be a bit strange. Maybe something like the following?

```
submissionDataTypes:
    files:
        enabled: <boolean>
        fields:
            - name: raw_reads
               multipleFiles: false
    consensusSequences:
        enabled: <boolean>
        <would we envision to have more things here?>
```

**Comment by theosanderson** [comment]
No strong feelings from me: your approach works for me. (Personally I don't mind the idea of something which can be a config object or can be `false/null` but I also don't prefer it to anything else, and it sounds like you do have a preference!)

**Comment by fhennig** [comment]
What about the output files? If we do

```yaml
submissionDataTypes:
    files:
        enabled: <boolean>
        fields:
            - name: raw_reads
              multipleFiles: false
    consensusSequences:
        enabled: <boolean>
        <would we envision to have more things here?>
```

Where do we define

```yaml
  publicFiles: --> What goes into SILO
    - name: raw_reads
      multipleFiles: false
    - name: aligned_reads
      multipleFiles: false
    - name: qc_plots
      multipleFiles: true
```

(I don't really have a pref either way on config stuff)

Maybe it'd be consistent to have the switch under `submissionDataTypes` but have the "schema" for which input and output files there are be in a separate config object. I mean, having input and output be different config sections is already differing to how we do it with the metadata - so we're not consistent - but I do think this is the simpler way to configure stuff (even though it might be less concise in some cases).
