### ISSUE TITLE
Initial file web upload for submission

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#3908]
Based on @theosanderson's prototype in #3859, let's add a file uploader to the submit page.

For the config:

```
  submissionFiles:
    - name: raw_reads
      multipleFiles: true
    - name: celebration_dance_video
      multipleFiles: false
```

The user should be able to add a folder like this:

```
/submissionId1/raw_reads.r1.fastq
/submissionId1/raw_reads.r2.fastq
/submissionId1/celebration_dance_video.mp4
```

It will request the pre-signed URLs for file upload (#3905), upload them and then send the following mapping to the submit endpoint (#3906):

```
  {
    submissionId1: {
      raw_reads: [
         { name: 'raw_reads.r1.fastq', id 'id-234'},
         { name: 'raw_reads.r2.fastq', id: 'id-235'}
      ],
      celebration_dance_video: { name: 'celebration_dance_video.mp4', id: 'id-236'}
    },
  }
```
