### ISSUE TITLE
Accepting reference-genome only, no genes

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#787]
When I set up an mpox test instance, I was lazy and didn't include any genes. This caused the website to crash as it expected an array in the config (IIRC)

This was the relevant part of the config.yaml:

```
referenceGenomes:
      nucleotideSequences:
        - name: "main"
          sequence: "ATTTTACTATTTTATTTAGTGTCTAGAAAAAAATGTGTGACC"
      genes:
```

This means there are `null` genes rather than an array. Maybe the website code expects an empty array instead of null?
